name: Rails CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start MySql
        run: sudo /etc/init.d/mysql start
      - name: Install bundle
        run: sudo gem install bundler:1.17.2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Rubocop
        run: |
              cd server
              DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=server_development TEST_DATABASE_NAME=server_test bundle exec rails db:create
              DATABASE_USERNAME=root DATABASE_PASSWORD=root DEVELOPMENT_DATABASE_NAME=server_development TEST_DATABASE_NAME=server_test bundle exec rspec
